-- MySQL Script generated by MySQL Workbench
-- Wed Dec 28 17:02:40 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema laboratory_2023
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `laboratory_day`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `laboratory_day` ;

CREATE TABLE IF NOT EXISTS `laboratory_day` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `day` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `users` ;

CREATE TABLE IF NOT EXISTS `users` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(64) NOT NULL,
  `password` VARCHAR(128) NOT NULL,
  `first_name` VARCHAR(64) NOT NULL,
  `middle_name` VARCHAR(64) NULL DEFAULT NULL,
  `last_name` VARCHAR(64) NOT NULL,
  `is_locked` TINYINT(1) NOT NULL DEFAULT 0,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  `created_by` INT(10) UNSIGNED NOT NULL,
  `updated_by` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC),
  INDEX `fk_users_users1_idx` (`created_by` ASC),
  INDEX `fk_users_users2_idx` (`updated_by` ASC),
  CONSTRAINT `fk_users_users1`
    FOREIGN KEY (`created_by`)
    REFERENCES `users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_users2`
    FOREIGN KEY (`updated_by`)
    REFERENCES `users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `profile`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `profile` ;

CREATE TABLE IF NOT EXISTS `profile` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  `created_by` INT(10) UNSIGNED NOT NULL,
  `updated_by` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_users_users1_idx` (`created_by` ASC),
  INDEX `fk_users_users2_idx` (`updated_by` ASC),
  INDEX `fk_users_profile1_idx` (`created_by` ASC),
  INDEX `fk_users_profile2_idx` (`updated_by` ASC),
  CONSTRAINT `fk_users_profile1`
    FOREIGN KEY (`created_by`)
    REFERENCES `users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_profile2`
    FOREIGN KEY (`updated_by`)
    REFERENCES `users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `laboratory_day_has_profile`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `laboratory_day_has_profile` ;

CREATE TABLE IF NOT EXISTS `laboratory_day_has_profile` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `laboratory_day_id` INT(10) UNSIGNED NOT NULL,
  `profile_id` INT(10) UNSIGNED NOT NULL,
  `meters_squared_per_sample` FLOAT UNSIGNED NOT NULL,
  `painted_samples_count` INT(10) UNSIGNED NOT NULL,
  `painted_meters_squared` FLOAT UNSIGNED NOT NULL,
  `kilograms_per_meter` FLOAT UNSIGNED NULL DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  `created_by` INT(10) UNSIGNED NOT NULL,
  `updated_by` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `laboratory_day_id_UNIQUE` (`laboratory_day_id` ASC),
  UNIQUE INDEX `profile_id_UNIQUE` (`profile_id` ASC),
  INDEX `fk_users_laboratory_day_profile1_idx` (`created_by` ASC),
  INDEX `fk_users_laboratory_day_profile2_idx` (`updated_by` ASC),
  CONSTRAINT `fk_profile_laboratory_day_has_profile`
    FOREIGN KEY (`profile_id`)
    REFERENCES `profile` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_laboratory_day_profile1`
    FOREIGN KEY (`created_by`)
    REFERENCES `users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_laboratory_day_profile2`
    FOREIGN KEY (`updated_by`)
    REFERENCES `users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `laboratory_month`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `laboratory_month` ;

CREATE TABLE IF NOT EXISTS `laboratory_month` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `month` INT(5) UNSIGNED NOT NULL,
  `year` INT(5) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `laboratory_month_has_day`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `laboratory_month_has_day` ;

CREATE TABLE IF NOT EXISTS `laboratory_month_has_day` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `laboratory_month_id` INT(10) UNSIGNED NOT NULL,
  `laboratory_day_id` INT(10) UNSIGNED NOT NULL,
  `kilograms` FLOAT UNSIGNED NULL DEFAULT NULL,
  `meters_squared` FLOAT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `laboratory_month_id_UNIQUE` (`laboratory_month_id` ASC),
  UNIQUE INDEX `laboratory_day_id_UNIQUE` (`laboratory_day_id` ASC),
  CONSTRAINT `fk_laboratory_day_laboratory_month_has_day`
    FOREIGN KEY (`laboratory_day_id`)
    REFERENCES `laboratory_day` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_laboratory_month_laboratory_month_has_day`
    FOREIGN KEY (`laboratory_month_id`)
    REFERENCES `laboratory_month` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `laboratory_month_has_day_has_chemicals`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `laboratory_month_has_day_has_chemicals` ;

CREATE TABLE IF NOT EXISTS `laboratory_month_has_day_has_chemicals` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `laboratory_month_has_day_id` INT(10) UNSIGNED NOT NULL,
  `name` VARCHAR(64) NOT NULL,
  `expense_per_meter_squared` FLOAT UNSIGNED NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  `created_by` INT(10) UNSIGNED NOT NULL,
  `updated_by` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `laboratory_month_has_day_id_UNIQUE` (`laboratory_month_has_day_id` ASC),
  INDEX `fk_users_laboratory_month_chemicals1_idx` (`created_by` ASC),
  INDEX `fk_users_laboratory_month_chemicals2_idx` (`updated_by` ASC),
  CONSTRAINT `fk_laboratory_month_has_day_laboratory_month_chemicals`
    FOREIGN KEY (`laboratory_month_has_day_id`)
    REFERENCES `laboratory_month_has_day` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_laboratory_month_chemicals1`
    FOREIGN KEY (`created_by`)
    REFERENCES `users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_laboratory_month_chemicals2`
    FOREIGN KEY (`updated_by`)
    REFERENCES `users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `permissions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `permissions` ;

CREATE TABLE IF NOT EXISTS `permissions` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `slug` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `slug_UNIQUE` (`slug` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `profile_has_lengths_perimeter`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `profile_has_lengths_perimeter` ;

CREATE TABLE IF NOT EXISTS `profile_has_lengths_perimeter` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `profile_id` INT(10) UNSIGNED NOT NULL,
  `length` FLOAT UNSIGNED NULL,
  `perimeter` FLOAT UNSIGNED NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_profile_profile_has_lengths_perimeter_idx` (`profile_id` ASC),
  CONSTRAINT `fk_profile_profile_has_lengths_perimeter`
    FOREIGN KEY (`profile_id`)
    REFERENCES `profile` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `roles` ;

CREATE TABLE IF NOT EXISTS `roles` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `slug` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `slug_UNIQUE` (`slug` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `role_has_permissions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `role_has_permissions` ;

CREATE TABLE IF NOT EXISTS `role_has_permissions` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `role_id` INT(10) UNSIGNED NOT NULL,
  `permission_id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_roles_role_has_permissions_idx` (`role_id` ASC),
  INDEX `fk_permissions_role_has_permissions_idx` (`permission_id` ASC),
  CONSTRAINT `fk_permissions_role_has_permissions`
    FOREIGN KEY (`permission_id`)
    REFERENCES `permissions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_roles_role_has_permissions`
    FOREIGN KEY (`role_id`)
    REFERENCES `roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `user_has_roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `user_has_roles` ;

CREATE TABLE IF NOT EXISTS `user_has_roles` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT(10) UNSIGNED NOT NULL,
  `role_id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_users_user_has_roles_idx` (`user_id` ASC),
  INDEX `fk_roles_user_has_roles_idx` (`role_id` ASC),
  CONSTRAINT `fk_roles_user_has_roles`
    FOREIGN KEY (`role_id`)
    REFERENCES `roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_user_has_roles`
    FOREIGN KEY (`user_id`)
    REFERENCES `users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
